### ISSUE TITLE
add more animals

### ISSUE THREAD

**Issue by cooljeanius** [ninjadev64/Fruity#2]
Personally I am a fan of guinea pigs, but really anything cute and furry will do... oh and I guess for the sake of the PureDarwin server, it should probably include a platypus, since Hexley is a platypus.

**Comment by ninjadev64** [comment]
Blame this: https://some-random-api.ml/animal/

**Comment by nekename** [comment]
Actually, they have added more animals since I implemented that command. I'll add the extra ones now :)
